### ISSUE TITLE
Define Integration Tests

### ISSUE THREAD

**Issue by assiaik** [assiaik/sprint1#37]
We begin to start setting integrations to oversee the project. By defining the tests, we can ensure we cover the entire project and ensure the whole webfront is running effectively

**Comment by Piri-Sai** [comment]
Integration tests are like checking if all the parts of our website or app work together smoothly. Integration tests make sure everything fits and functions correctly when they're connected. For instance, if we have a login feature, an integration test might confirm that a user can log in successfully and then check if they can access their profile page afterwards. These tests help ensure that our website or app behaves as expected when all the parts work together, which is important for providing a good user experience.
